use_frameworks!
inhibit_all_warnings!

target 'NNetwork_Example' do
  pod 'NNetwork', :path => '../' , :inhibit_warnings => false
  pod 'NNCore', :path => '../../NNCore'
  target 'NNetwork_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
end
